<!doctype html>
<html lang="id">
<head>
    <meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Pengaturan Perusahaan - PaySync</title>
    @include('payflow.partials.styles')
    <style>[x-cloak]{display:none!important}.settings-tabs{display:flex;gap:8px;border-bottom:1px solid var(--line);margin-bottom:18px}.settings-tabs button{border:0;background:none;padding:10px 14px;cursor:pointer;color:var(--muted)}.settings-tabs button.active{color:var(--brand);border-bottom:2px solid var(--brand);font-weight:700}</style>
</head>
<body x-data="{ tab: 'company' }" x-cloak>
<main style="max-width:1100px;margin:0 auto;padding:32px 20px;">
    @include('payflow.partials.brand')
    <div class="page-head" style="margin-top:24px;"><div><h1>Pengaturan Perusahaan</h1><p class="muted">Kelola profil, anggota, dan riwayat perubahan workspace.</p></div><a class="btn btn-secondary" href="{{ route('dashboard.hr') }}">Kembali</a></div>
    @if(session('status'))<div class="card" style="padding:14px;margin-bottom:16px;border-left:4px solid var(--green);">{{ session('status') }}</div>@endif
    <nav class="settings-tabs" aria-label="Settings tabs"><button :class="{active:tab==='company'}" @click="tab='company'">Profil Perusahaan</button><button :class="{active:tab==='users'}" @click="tab='users'">Manajemen User</button><button :class="{active:tab==='audit'}" @click="tab='audit'">Riwayat Perubahan</button></nav>
    <section x-show="tab==='company'"><form method="POST" action="{{ route('settings.company.update') }}" class="card form-stack">@csrf @method('PUT')<div class="grid grid-2"><label class="field"><span>Nama perusahaan</span><input class="input" name="name" value="{{ old('name',$company->name) }}" required>@error('name')<small class="field-error">{{ $message }}</small>@enderror</label><label class="field"><span>Industri</span><input class="input" name="industry" value="{{ old('industry',$company->industry) }}"></label><label class="field"><span>Ukuran</span><input class="input" name="size" value="{{ old('size',$company->size) }}"></label><label class="field"><span>Payroll cut-off</span><input class="input" type="number" name="payroll_cut_off" min="1" max="28" value="{{ old('payroll_cut_off',$company->payroll_cut_off) }}"></label><label class="field"><span>Tanggal bayar</span><input class="input" type="number" name="pay_date" min="1" max="31" value="{{ old('pay_date',$company->pay_date) }}"></label></div><button class="btn btn-primary">Simpan Perubahan</button></form></section>
    <section x-show="tab==='users'" x-cloak class="card" style="padding:0;"><div class="table-wrap"><table><thead><tr><th>Nama</th><th>Email</th><th>Role</th><th>Status</th><th>Aksi</th></tr></thead><tbody>@forelse($users as $user)<tr><td>{{ $user->name }}</td><td>{{ $user->email }}</td><td><form method="POST" action="{{ route('settings.users.role',$user) }}" style="display:flex;gap:6px;">@csrf @method('PUT')<select class="input" name="role"><option value="hr_manager" @selected($user->role==='hr_manager')>HR Manager</option><option value="finance_manager" @selected($user->role==='finance_manager')>Finance Manager</option><option value="employee" @selected($user->role==='employee')>Employee</option></select><button class="btn btn-secondary">Simpan</button></form></td><td><span class="badge {{ $user->status === 'active' ? 'badge-green' : 'badge-amber' }}">{{ ucfirst($user->status) }}</span></td><td><form method="POST" action="{{ route('settings.users.deactivate',$user) }}" onsubmit="return confirm('Nonaktifkan user ini?')">@csrf @method('DELETE')<button class="btn btn-danger">Nonaktifkan</button></form></td></tr>@empty<tr><td colspan="5" style="text-align:center;padding:24px;">Belum ada anggota.</td></tr>@endforelse</tbody></table></div></section>
    <section x-show="tab==='audit'" x-cloak class="card" style="padding:0;"><div class="table-wrap"><table><thead><tr><th>Waktu</th><th>User</th><th>Field</th><th>Nilai Lama</th><th>Nilai Baru</th></tr></thead><tbody>@forelse($auditLogs as $log)<tr><td>{{ $log->changed_at?->format('d M Y H:i') }}</td><td>{{ $log->user?->name ?? '-' }}</td><td>{{ $log->field_changed }}</td><td>{{ $log->old_value ?? '-' }}</td><td>{{ $log->new_value ?? '-' }}</td></tr>@empty<tr><td colspan="5" style="text-align:center;padding:24px;">Belum ada riwayat perubahan.</td></tr>@endforelse</tbody></table></div></section>
</main><script defer src="{{ asset('vendor/alpinejs/cdn.min.js') }}"></script>
</body></html>
